# Generated by Django 4.1.2 on 2022-10-20 01:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("experiences", "0004_experience_category"),
        ("rooms", "0005_room_category"),
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ReveiwModel",
            new_name="Review",
        ),
    ]
